// File generated by FlutterFire CLI & configured with dotenv.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey:
        dotenv.env['FIREBASE_WEB_API_KEY'] ??
        'AIzaSyAMdRzLQcGyHv6673tCHChQa1VkjYkZv5w',
    appId:
        dotenv.env['FIREBASE_WEB_APP_ID'] ??
        '1:308103221424:web:40ab4cba52ca9f671deb75',
    messagingSenderId:
        dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '308103221424',
    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'transitgo-1b966',
    authDomain:
        dotenv.env['FIREBASE_WEB_AUTH_DOMAIN'] ??
        'transitgo-1b966.firebaseapp.com',
    storageBucket:
        dotenv.env['FIREBASE_STORAGE_BUCKET'] ??
        'transitgo-1b966.firebasestorage.app',
    measurementId: dotenv.env['FIREBASE_WEB_MEASUREMENT_ID'] ?? 'G-Y1QS8B5ZHV',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey:
        dotenv.env['FIREBASE_ANDROID_API_KEY'] ??
        'AIzaSyA3s5xUHPmaGrGAVT8Fmy7R89EKhdxTxdo',
    appId:
        dotenv.env['FIREBASE_ANDROID_APP_ID'] ??
        '1:308103221424:android:12aa5132f6130fc21deb75',
    messagingSenderId:
        dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '308103221424',
    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'transitgo-1b966',
    storageBucket:
        dotenv.env['FIREBASE_STORAGE_BUCKET'] ??
        'transitgo-1b966.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey:
        dotenv.env['FIREBASE_IOS_API_KEY'] ??
        'AIzaSyCThSgqaBnMh4x63oV8KdpY-EPgl9qgt5I',
    appId:
        dotenv.env['FIREBASE_IOS_APP_ID'] ??
        '1:308103221424:ios:7e3e57a15a07570c1deb75',
    messagingSenderId:
        dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '308103221424',
    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'transitgo-1b966',
    storageBucket:
        dotenv.env['FIREBASE_STORAGE_BUCKET'] ??
        'transitgo-1b966.firebasestorage.app',
    iosBundleId:
        dotenv.env['FIREBASE_IOS_BUNDLE_ID'] ?? 'com.hyperlogics.transitGo',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey:
        dotenv.env['FIREBASE_IOS_API_KEY'] ??
        'AIzaSyCThSgqaBnMh4x63oV8KdpY-EPgl9qgt5I',
    appId:
        dotenv.env['FIREBASE_IOS_APP_ID'] ??
        '1:308103221424:ios:7e3e57a15a07570c1deb75',
    messagingSenderId:
        dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '308103221424',
    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'transitgo-1b966',
    storageBucket:
        dotenv.env['FIREBASE_STORAGE_BUCKET'] ??
        'transitgo-1b966.firebasestorage.app',
    iosBundleId:
        dotenv.env['FIREBASE_IOS_BUNDLE_ID'] ?? 'com.hyperlogics.transitGo',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey:
        dotenv.env['FIREBASE_WINDOWS_API_KEY'] ??
        'AIzaSyAMdRzLQcGyHv6673tCHChQa1VkjYkZv5w',
    appId:
        dotenv.env['FIREBASE_WINDOWS_APP_ID'] ??
        '1:308103221424:web:86fd143f903ea19a1deb75',
    messagingSenderId:
        dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '308103221424',
    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'transitgo-1b966',
    authDomain:
        dotenv.env['FIREBASE_WEB_AUTH_DOMAIN'] ??
        'transitgo-1b966.firebaseapp.com',
    storageBucket:
        dotenv.env['FIREBASE_STORAGE_BUCKET'] ??
        'transitgo-1b966.firebasestorage.app',
    measurementId:
        dotenv.env['FIREBASE_WINDOWS_MEASUREMENT_ID'] ?? 'G-HHNTQ0HWZZ',
  );
}
